### ISSUE TITLE
Файловая структура компонентов

### ISSUE THREAD

**Issue by akuznetsov-md** [dmzebrov/mercdev_test_react#1]
Судя по всему, ты решил сделать файловую структуру "по БЭМу". Рекомендуя БЭМ, я давал ссылку только на базовые понятия, которые помогают плавно перейти к компонентному подходу при разработке интерфейсов. Полностью переносить всю БЭМ-инфраструктуру не стоит: мы не практикуем такое в компании. 

Я обычно делаю один файл стилей для компонента и храню с таким же названием в папке компонента:
```
- components/MyComponent/MyComponent.js
- components/MyComponent/MyComponent.css
```
Либо в случае с CSS-in-JS решениями
```
- components/MyComponent/MyComponent.js
- components/MyComponent/MyComponent.style.js
```

Кстати, ты можешь объяснить в чем выгода выделения CSS элементов и модификаторов в отдельные файлы?

**Comment by dmzebrov** [comment]
Все верно, применил БЭМ. Думал, что это обязательное условие.

Во время работы понял, что разделение и так небольшого файла стилей компонента на более мелкие не имеет смысла. Более того, это даже усложняет работу с компонентом.

Очевидно, что выделения CSS элементов и модификаторов в отдельные файлы имеет смысл когда CSS файл разрастается. Выделение нужно для упрощения поиска/чтения/редактирования стилей.


Так же решил избавиться от компонентов auth-page__background/__logo, так как считаю это лишним усложнением структуры, не приносящим особого профита.
