### ISSUE TITLE
Поля ввода подсвечиваются невалидными еще до окончания ввода

### ISSUE THREAD

**Issue by akuznetsov-md** [dmzebrov/mercdev_test_react#10]
Такой подход является плохой практикой с т.з. UX. Пользователь только начал что-то вводить, а мы ему уже кричим, что он ошибся. Не надо так

**Comment by dmzebrov** [comment]
Я прекрасно понимаю, что сразу кричать об ошибке - не лучшая практика. Именно поэтому, я добавил булев параметр "displayError" в компонент input, который активируется только после первого расфокуса с конкретного input'а.

На мой взгляд позитивный workflow будет работать в большинстве случаев, при этом, если пользователь ошибся, во время исправления он будет видеть результат сразу.
